### ISSUE TITLE
Tutorial in `lvl_opening`

### ISSUE THREAD

**Issue by mestiez** [studio-minus/madness-interactive-reloaded#1]
In `lvl_opening` of the standard campaign, there should be a little tutorial to explain controls and common game mechanics.
![Tutorial1](https://github.com/user-attachments/assets/689b14a8-a689-4a08-9e64-fa5733af22ad)
![Tutorial2](https://github.com/user-attachments/assets/e16749ad-4d50-4303-bac1-82e76b84c714)
![Tutorial3](https://github.com/user-attachments/assets/32946436-e2dc-4091-a6db-b5e789549070)

**Comment by mestiez** [comment]
**Things we should explain**

- How to attack
- How to do melee
- How to Jump-Dodge, and why
- Throw weapons (very effective!)
- How to pick up weapons
- Abilities (?? not part of main campaign lol)
- What dodge is
- Dodge regeneration
- Deflection
- Parrying
- Blocking
- How to proceed to the next level
- How to dodge/deflect accurate shots
- You can't reload

**Comment by Dikkiedink** [comment]
![PROCEED](https://github.com/user-attachments/assets/173a62e7-5d20-4df8-a9db-988573c16d7e)
![ATTACK](https://github.com/user-attachments/assets/637d733d-b4f3-47f1-a586-1b79822caf86)
![PICKUP](https://github.com/user-attachments/assets/5a3fae04-52b1-41e7-9518-ffda35871d09)
![THROW](https://github.com/user-attachments/assets/fb2460b4-ade6-4ee0-a1db-405bf2940168)
![DODGE](https://github.com/user-attachments/assets/ee809c8b-8e86-4de8-aad1-959987b9bc01)
![EMPTY](https://github.com/user-attachments/assets/09a25104-8876-464c-aa8b-da307e516c93)

**Comment by Dikkiedink** [comment]
![MELEE](https://github.com/user-attachments/assets/3ef97e07-f2cc-4815-add0-47b057942276)
![AIM](https://github.com/user-attachments/assets/20639557-05d5-4536-b91c-a53596f51f35)
![BLOCK1](https://github.com/user-attachments/assets/7f51a0de-3285-4a93-b95a-f84443529b60)
![BLOCK2](https://github.com/user-attachments/assets/e6a76acb-8f97-4c4d-aff2-a0e56759bcc6)
![ABILITIES](https://github.com/user-attachments/assets/51ea634a-49be-4452-827a-5a46ae3710e4)

**Comment by Dikkiedink** [comment]
press space to dodge to a jump ddoge

**Comment by mestiez** [comment]
Done i think
