### ISSUE TITLE
Incorrectly Labeled MC2 Track (NOT A TROLL)

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#104]
**Description**
The track for MC2 is not "Unknown." It is Fancy Fiddle by Arthur Smith: https://www.youtube.com/watch?v=S98Dp-gej7A

**Reasoning**
It would sound 5x better and you can correctly credit the song! (plus, new parts able to be looped around!)

**Additional context**
cheese

**Comment by Dikkiedink** [comment]
You're right! Fixed it
