### ISSUE TITLE
Fixing mc 7 hank bandana 

### ISSUE THREAD

**Issue by Unami45** [studio-minus/madness-interactive-reloaded#108]
**Description**
this gap is soooo weird

Game:
![image](https://github.com/user-attachments/assets/b313bd1f-7132-44e0-87e7-90a8caf45b2e)

Series:
![image](https://github.com/user-attachments/assets/6807445d-4e0a-4059-a437-a89245500e6c)

**Reasoning**
fidelity to the show

**Comment by Unami45** [comment]
Also.., i dont know man, but Dikkiedik's MC7 Hank version seems more accurate... sorry Koof :(
![image](https://github.com/user-attachments/assets/a4a6ed2b-929d-412c-89e0-288e199b6b26)

**Comment by Dikkiedink** [comment]
Hello! Use "Metal Jaw 2" as a base layer for the head if you want to play as MC7 Hank! It'll look great :D

**Comment by Unami45** [comment]
> Hello! Use "Metal Jaw 2" as a base layer for the head if you want to play as MC7 Hank! It'll look great :D

@Dikkiedink Yeah, i figured this out! But something about his mouth bandana seems weird. I think the model of his bandana that is in the game is too straight, besides being too high on his face, in the animated version (and in yours too), his bandana seems more accurate, being slightly tilted downwards.

**Comment by Koofa** [comment]
I don't know what this means, what did I make?

**Comment by Unami45** [comment]
> I don't know what this means, what did I make?

his bandana is kinda weird...

**Comment by Koofa** [comment]
Why are you convinced I made them lol

**Comment by Unami45** [comment]
> Why are you convinced I made them lol

bro
![Screenshot_20240911_125017_Chrome](https://github.com/user-attachments/assets/297d7d68-e2a2-4f09-8e5b-71768b2a6775)

**Comment by Koofa** [comment]
Do you see how Hank's skin layer looks normal in this screenshot? It's because he has the correct one. Also I think I was referring to drawing the other two hanks, and making the `.look` file something idk
