### ISSUE TITLE
Flying with Savior disk on lvl_dangerous_stair makes the player clip through the roof

### ISSUE THREAD

**Issue by Balage0429** [studio-minus/madness-interactive-reloaded#124]
i think the image speaks for itself. 
![image](https://github.com/user-attachments/assets/88d9f850-2a98-49ce-b3c3-33f21b45d992)

**Comment by mestiez** [comment]
It doesn't

**Comment by SoapFif** [comment]
i think they mean like the guy's head is in the ceiling

**Comment by Balage0429** [comment]
> i think they mean like the guy's head is in the ceiling

yes

**Comment by Balage0429** [comment]
> It doesn't

My characters head is INSIDE of the ceiling lol

**Comment by Koofa** [comment]
Yeah but please follow the instructions, we can't do anything with a report like this. Not enough information.
![image](https://github.com/user-attachments/assets/7408350b-c410-4c8e-99e7-45a2b44ac669)

**Comment by Balage0429** [comment]
Alright.

**Comment by Balage0429** [comment]
> Yeah but please follow the instructions, we can't do anything with a report like this. Not enough information. ![image](https://private-user-images.githubusercontent.com/85030177/365724668-7408350b-c410-4c8e-99e7-45a2b44ac669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDY2NTksIm5iZiI6MTcyNTkwNjM1OSwicGF0aCI6Ii84NTAzMDE3Ny8zNjU3MjQ2NjgtNzQwODM1MGItYzQxMC00YzhlLTk5ZTctNDVhMmI0NGFjNjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE4MjU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4ZmVjNjU3MmIzZWVjNDc5YmVhYTc2NGMxY2IyNjBjMzc0M2JhZWQxN2RjYzBjMTQxYmM1YWUzZTRiMjI1NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wwAubDeG1tYJ5ZZ7Eg4vRexYVyFRSfTNc0Kx39P4kw8)

My characters head is inside of the wall when i fly.
Steps: 1.choose Savior improbability disk.
2. Get on the level that can be seen in the screenshot
3. Fly at the top of the stairs.
 Expected behavior: the character is not supposed to clip trough the ceiling.i think there should be a flight height limit like thing.

Windows 10( not activated)
Version : 0.48.4
