### ISSUE TITLE
Game isn't starting up at all.

### ISSUE THREAD

**Issue by eloads** [studio-minus/madness-interactive-reloaded#125]
**Describe the bug**
The game isn't starting up. 

**Steps to reproduce**
I extracted the game's archive, and then clicked on MIR.exe. It didn't even start or anything. NOTHING happened at ALL.

**Expected behavior**
The game starts up

**Video**

https://github.com/user-attachments/assets/8347875f-e09c-47ab-82ea-7635a9cc3356

**Desktop**
OS : Windows x64
Version : 0.48.4

**Comment by ionutz799** [comment]
Do you have the required programs installed? If you do, then i'd suggest trying to run it as administrator. that's what I would try to do, at least.

**Comment by eloads** [comment]
> Do you have the required programs installed? If you do, then i'd suggest trying to run it as administrator. that's what I would try to do, at least.

I tried running it as an admin, as seen in the video at the end, and I installed all the required programs they listed before this.

**Comment by ionutz799** [comment]
Could it be your antivirus? Maybe its thinking that the game is some sort of malware. Im not very sure what this could be.

**Comment by maggain** [comment]
i have the exact same issue, did everything specified and still didnt work, even turned off my antivirus and STILL doesn't open

**Comment by mestiez** [comment]
You haven't provided nearly enough information

**Comment by maggain** [comment]
> You haven't provided nearly enough information

..there IS no more information, I had the exact same bug, and cannot play the game because of it, it quite literally just does not open no matter what is done, instead, when clicked, the cursor turns to a circle for a few seconds, but nothing

**Comment by eloads** [comment]
> You haven't provided nearly enough information

I've provided ALL the information I have. I have all the required programs installed, I provided the OS, the game version and video evidence.

**Comment by eloads** [comment]
ALSO, I have solved the problem. You have to go into properties(security I think), and there will be an option to 'unblock the program'. Check the box, apply, and you should be good to go.

**Comment by Valentine481** [comment]
> ALSO, I have solved the problem. You have to go into properties(security I think), and there will be an option to 'unblock the program'. Check the box, apply, and you should be good to go.

how you make that?
I tried to unblock in windows defender but nothing happens

**Comment by bloodysnowlol** [comment]
How do I solve this?

**Comment by bloodysnowlol** [comment]
> ALSO, I have solved the problem. You have to go into properties(security I think), and there will be an option to 'unblock the program'. Check the box, apply, and you should be good to go.

how?

**Comment by LyssJack** [comment]
> ALSO, I have solved the problem. You have to go into properties(security I think), and there will be an option to 'unblock the program'. Check the box, apply, and you should be good to go.

Bro how you do that? Have the same trouble.
