### ISSUE TITLE
Weapon/armor editor

### ISSUE THREAD

**Issue by Balage0429** [studio-minus/madness-interactive-reloaded#126]
Can someone help me where can i find the weapon editor? i cant find it. or, it doesnt even exists yet?
 @mestiez Pretty please help me 🥺

**Comment by Takua-The-Tohunga** [comment]
### There Is a Weapon editor. Its just you dont know how to gain access to the editor. dont ask me how to go to the editor because idk how to go to it...

**Comment by Takua-The-Tohunga** [comment]
Ok, I found out how to access the editors, press f12 and type WeaponEditor (or) LevelEditor

There is most likely a More editors out there but i have yet to find them

**Comment by Balage0429** [comment]
> Ok, I found out how to access the editors, press f12 and type WeaponEditor (or) LevelEditor
> 
> There is most likely a More editors out there but i have yet to find them

Thank you!

**Comment by Balage0429** [comment]
and how do i import files? i have JPG files.

**Comment by mestiez** [comment]
This is not the place for discussion like this
