### ISSUE TITLE
unable to move to the next room/can't climb ladder in lvl_ladder

### ISSUE THREAD

**Issue by Littboii** [studio-minus/madness-interactive-reloaded#134]
**Describe the bug**
After finishing lvl_ladder, the animation to climb the ladder doesn't start and I cannot go to the next
room.
**Steps to reproduce**
I'm not really sure how to reproduce it, I think it might be the radgoll blocking me from climbing up, not sure tho.

**Expected behavior**
Grunt man going up the ladder

**Screenshots or video**
here is a video of the animation not working

https://github.com/user-attachments/assets/47645857-6c23-4157-8bfb-d2034f812516

**Desktop** :
 - OS: Windows 10
 - Version [e.g. 0.48.3]

**Comment by r5styy** [comment]
hold space next to the ladder to climb
