### ISSUE TITLE
How do I open the Editors?

### ISSUE THREAD

**Issue by BuildersHut** [studio-minus/madness-interactive-reloaded#142]
How in the world do I open the Level Editor, Weapon Editor, and Armor Editor?

**Comment by mrmadnezz** [comment]
F12, and then leveleditor or weaponeditor. No idea how to open the armor editor tho

**Comment by BuildersHut** [comment]
> F12, and then leveleditor or weaponeditor. No idea how to open the armor editor tho

Thanks!
