### ISSUE TITLE
Level Editor controls

### ISSUE THREAD

**Issue by BuildersHut** [studio-minus/madness-interactive-reloaded#147]
I've pressed EVERY button on my keyboard and clicked EVERY mouse button. And I still don't know how to add things in like the backround and stuff as seen in the gameplay trailer. What are the controls?!

**Comment by mestiez** [comment]
All will be explained in https://studiominus.nl/mir/docs/ but this is currently a WIP.

In the meantime, the controls are very similar to Blender:

Shift+A to add objects
R to rotate
G to move
S to scale
