### ISSUE TITLE
Character editor, clipping accesories

### ISSUE THREAD

**Issue by Crypto-cry** [studio-minus/madness-interactive-reloaded#149]
**Description*
There seems to be an issue with the way accessories are rendered at least at the character customization menu. It seems like when you put on an accessories that is way too high like in this case the Top Hat it just doesn't render. This also applies in the main menu however in game it is just fine.

**Screenshot*
![image](https://github.com/user-attachments/assets/f72a4d22-1c7f-4c43-bbde-8edb560432e1)

**Desktop:**
 - OS: [Windows]

**Comment by dch-GH** [comment]
@mestiez This is because of:
https://github.com/studio-minus/madness-interactive-reloaded/blob/67726ec57c7d5f48a7750b3995867baa11af36e2/src/MadnessInteractiveReloaded/Character%20creation/Systems/CharacterCreationSystem.cs#L269-L272

It moves it down and cuts off the top.
