### ISSUE TITLE
game literally does not open 

### ISSUE THREAD

**Issue by maggain** [studio-minus/madness-interactive-reloaded#157]
**Describe the bug**
Did all the exact steps to download it, turned off my antivirus, even ran as administrator, absolutely nothing happens.

**Expected behavior**
Game opens, hooray.

**Screenshots or video**
Someone else has already posted a video with the exact same problem, literally the same.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 22H2
**Additional context**
Thats it, jus' doesnt work

**Comment by EEASAS** [comment]
i'm having same problem

**Comment by civinum** [comment]
Try troubleshooting the exe. always works for me

**Comment by mestiez** [comment]
Duplicate of #125
