### ISSUE TITLE
"PROTAGONIST" improbability disk

### ISSUE THREAD

**Issue by unfuny1337** [studio-minus/madness-interactive-reloaded#176]
**Description**
an improbability disk, adds bullet time, enhanced hp, and dual-wielding ability

**Reasoning**
i mean it sounds pretty cool, also makes you hank

**Additional context**
![Безымянный2](https://github.com/user-attachments/assets/ae0f172e-ed65-4745-bab5-01f3b947e4aa)

**Comment by Vuno12** [comment]
max payne in madness combat?!!??
