### ISSUE TITLE
Add this cursor to the game

### ISSUE THREAD

**Issue by mcduckpop** [studio-minus/madness-interactive-reloaded#182]
In Madness Project Nexus, there's this pointer, please add this as an option for people who are struggling
![Screenshot 2024-09-10 225644](https://github.com/user-attachments/assets/59ca34f8-d3a7-4dea-b33e-6b560f64a10e)

**Comment by Orsoniks** [comment]
a crosshair's gonna be needed eventually yeah

**Comment by mestiez** [comment]
Not this one though

**Comment by mcduckpop** [comment]
wdym?
