### ISSUE TITLE
add some actual visual representation of your health

### ISSUE THREAD

**Issue by mcduckpop** [studio-minus/madness-interactive-reloaded#183]
Sort of like in Madness Project Nexus
![image](https://github.com/user-attachments/assets/f93e39cc-a306-4a74-830a-813a909f4892)

**Comment by Koofa** [comment]
It doesn't really fit with the minimum UI style of the game, but maybe a visual representation of health with blood vessels around the border of the screen?

**Comment by mcduckpop** [comment]
That should (also please add this https://github.com/studio-minus/madness-interactive-reloaded/issues/182)
