### ISSUE TITLE
Rename "Gol3m" base layer head option to "Go3lm"

### ISSUE THREAD

**Issue by ghost** [studio-minus/madness-interactive-reloaded#191]
"The G03LM (Standing for Generation-03, Limited Model)" - MC Wiki

**Comment by spaghettimuncher** [comment]
dude nobody cares

**Comment by mestiez** [comment]
My goodness

**Comment by Dikkiedink** [comment]
Fixed it! I can't believe I've always read it as "Gol3m" ...
