### ISSUE TITLE
Rich Enemies not spawning + 3 smaller things

### ISSUE THREAD

**Issue by CheeseDealerUno** [studio-minus/madness-interactive-reloaded#200]
**Describe the bug**
So, I had encountered this bug a couple times before. Basically, from all I can tell, enemies will straight up not spawn in this section. 4 will spawn with Rich when his timer trigger is up for him to, y'know, spawn. Additionally, hitting "Retry" doesn't seem to fix this problem either, same with level select, you have to restart the entire game. There's also a texture bug on the left side of the Rich arena that has weird overlapping (Most prominent with larger guns/melee weapons).

**Steps to reproduce**
For the life of me, I have no idea how or why this happens. Maybe a death causes this? I had died in the elevator section prior to this one, there have also been a couple of times I haven't died on the elevator and they still spawn? I'm honestly not sure. It could just be something that happens randomly.

Video links since the file is too large: 
https://medal.tv/games/madness-interactive-reloaded/clips/iFcvwmW9AZ2b-FWF1/d13374qCTLtP?invite=cr-MSxRNUEsMjQzNTIzMDk2LA

Me trying to restart via level select:
https://medal.tv/games/madness-interactive-reloaded/clips/iFcSt2uh6SzPf74HH/d13375XZW6ov?invite=cr-MSwwQUssMjQzNTIzMDk2LA

Me restarting the game and the enemies spawn again:
https://medal.tv/games/madness-interactive-reloaded/clips/iFcVlizOLNVK18eec/d13377NQ1TqR?invite=cr-MSw4OXIsMjQzNTIzMDk2LA

Me testing to see if an elevator death causes the no spawning:
https://medal.tv/games/madness-interactive-reloaded/clips/iFd3gVPnvejLSqnqs/d1337O3NYi5J?invite=cr-MSxFV1UsMjQzNTIzMDk2LA

At the start of level 1, you can dodge to get out of the getup animation, though, you won't be able to move with left or right. The cause being no disabling on the dodge button. Pretty cool speedrun trick though.

Video of this:
https://medal.tv/games/madness-interactive-reloaded/clips/iFd7QMHb5sj_w8-UD/d1337sxtV7zq?invite=cr-MSxmWG4sMjQzNTIzMDk2LA

The last thing I have to mention is how much this pisses me off lol (I have beaten the game, yes):
![image](https://github.com/user-attachments/assets/59247b61-a73f-4775-b419-7033aa6d4b70)

**Desktop**
 - OS: Windows
 - Version: 0_48_7 (Also happened on version 0_48_5, could've also been in older updates)

**Comment by mestiez** [comment]
This happens when you have the Menagerie disk enabled (see #94).

Also please try not to group bug reports, because then we'll have no way to track the progress of each of them.

**Comment by CheeseDealerUno** [comment]
Oh, I'm sorry. I didn't know if you guys preffered it this way or not. I also didn't know the disk affected it. Thanks for the info.
