### ISSUE TITLE
Missing hands

### ISSUE THREAD

**Issue by Wehrmachgt** [studio-minus/madness-interactive-reloaded#201]
**Describe the bug**
1. My charachter and other grunts don't have hands, i can't hit.
Some grunts though have hands and can hit me.

**Steps to reproduce**
1. Launch game and start campaign

**Expected behavior**
Uhhh melee combat?

**Screenshots or video**
![image](https://github.com/user-attachments/assets/21a5b8e4-7891-4782-885a-6f9c6ad23be0)

**Desktop:**

 - OS: Windows 10 Pro x64
 - Version: 0.48.7.0

**Comment by InputSoldatcc** [comment]
the dreaded issue #38

**Comment by mestiez** [comment]
Duplicate of #38
