### ISSUE TITLE
Bug: Entering Doors Too Fast Will Crash The Game.

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#205]
**Describe the bug**
Exactly what the title says. I wasn't recording, sadly.

**Steps to reproduce**
1. Enter Doors That Transition Too Fast.
2. Watch It Go Wrong. So Wrong.

**Expected behavior**
For the doors to work?

**Screenshots or video**
bug report
![image](https://github.com/user-attachments/assets/5c50e086-a427-4816-959b-0aeff1fa7454)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 0.48.8

**Additional context**
why

**Comment by SacredSven** [comment]
it happened AGAIN 
![image](https://github.com/user-attachments/assets/9095ffcf-df78-4dfa-88ef-b8439313d573)

**Comment by Koofa** [comment]
oh no, we're you trying to pick up a weapon while walking through a door?

**Comment by mestiez** [comment]
fixed
