### ISSUE TITLE
Game's fonts should support Cyrillic

### ISSUE THREAD

**Issue by Krasapan** [studio-minus/madness-interactive-reloaded#209]
**Describe the bug**
Cyrillic letters are invisible: game's fonts don't support Cyrillic (I think)

**Steps to reproduce**
1. Download and extract the mod template
2. Add the default `en-GB.json` locale from the source repo to you mod's assets structure `ModName/assets/locale/en-GB.json`, rename `"DisplayName"` string to your own language, rename the file name and `"Culture"` string to the corresponding locale code
3. Do the translation to your own Cyrillic language
4. Build your mod
5. Set your language in game's options

**Expected behavior**
Custom language works, but Cyrillic is not being displayed

**Screenshots or video**
![2024-09-13_144155](https://github.com/user-attachments/assets/879bfdb5-2934-446d-be0d-8eb7711dce88)

https://github.com/user-attachments/assets/92c18711-0b7d-495e-966f-f88c5399f473

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version: 0.48.8

**Additional context**
I added each letter of the Ukrainian alphabet to the main menu strings to test the custom locale

**Comment by SacredSven** [comment]
I believe that this may be due to the Engine not knowing how to load fonts from MODS in specific, This may need to be added.

**Comment by mestiez** [comment]
The engine does know how to load fonts from mods. The described issue is accurate: the built-in fonts don't support Cyrillic. However, this isn't a bug. Adding Cyrillic characters would increase the font file size and I figured this is unnecessary for the base game. 

You can always replace the base fonts with versions that include more characters, and include these in your mod.

**Comment by SacredSven** [comment]
> The engine does know how to load fonts from mods. The described issue is accurate: the built-in fonts don't support Cyrillic. However, this isn't a bug. Adding Cyrillic characters would increase the font file size and I figured this is unnecessary for the base game.
> 
> You can always replace the base fonts with versions that include more characters, and include these in your mod.

Ah, my mistake. I misunderstood how the engine uses fonts. I thought it needed them in a specific location or it wouldn't load the fonts.

**Comment by Krasapan** [comment]
> The engine does know how to load fonts from mods. The described issue is accurate: the built-in fonts don't support Cyrillic. However, this isn't a bug. Adding Cyrillic characters would increase the font file size and I figured this is unnecessary for the base game.
> 
> You can always replace the base fonts with versions that include more characters, and include these in your mod.

Got it
I looked up these fonts and they're in some weird .fw format that I can't find information about, what kind of font format is it and how can I convert regular font formats to this one
So it isn't drag-n-drop .otf/.ttf solution like I thought it would be
