### ISSUE TITLE
Make modding core game mechanics possible

### ISSUE THREAD

**Issue by Krasapan** [studio-minus/madness-interactive-reloaded#212]
**Description**
As I understand you can't edit game's functionality, only add new functionality that don't mess us with game's core
Possible solution: make component classes being able to be inherited by mods

**Reasoning**
Currently people can make mods that only add functionality that doesn't edit game's core mechanics like player movement, camera, gun mechanics etc. I tried to mess up with the camera component, but interaction is very limited. Though classes are public, they are not inheritable. Being able to add completely new mechanics will allow endless possibilities for modding, from custom visuals like parallax to new gun projectile types

**Comment by dch-GH** [comment]
Since we are shipping with Harmony (https://harmony.pardeike.net/articles/intro.html), you should be able to use `Prefix` and `Postfix` to modify methods in the game to do what you want. Also, our classes are not sealed so you should be able to inherit them, If you mean that the members are private instead of protected, we may be able to do something about that.

**Comment by mestiez** [comment]
The game is open source so if you want to make any big changes, simply create a pull request! :)

**Comment by Krasapan** [comment]
> Since we are shipping with Harmony (https://harmony.pardeike.net/articles/intro.html), you should be able to use `Prefix` and `Postfix` to modify methods in the game to do what you want. Also, our classes are not sealed so you should be able to inherit them, If you mean that the members are private instead of protected, we may be able to do something about that.

Yeah just checked again and class inheritance works, but methods in them can't be overriden. But you said about that Harmony thing that allows doing that, so I'll look into it, thanks for the help!
Speaking of members, I wanted to access [`playerPos`](https://github.com/studio-minus/madness-interactive-reloaded/blob/fdbbdd286fd9cd285dd740bf4648cb8b3bd5a6ad/src/MadnessInteractiveReloaded/Camera/Components/CameraMovementComponent.cs#L144) in [`CameraMovementComponent`](https://github.com/studio-minus/madness-interactive-reloaded/blob/main/src/MadnessInteractiveReloaded/Camera/Components/CameraMovementComponent.cs#L144), but couldn't because local variables are private by default. That's when I started to consider overriding the whole class or method with the same code that will have modified only [`playerPos`]. Maybe such local variables in methods should be more accessible, but if Harmony can fully override methods, then maybe that would be enough for a solution



> The game is open source so if you want to make any big changes, simply create a pull request! :)

Sure! Not planning to make anything significant for pull request yet, will do it if I make something!

**Comment by Krasapan** [comment]
I think I can close this because I managed to create a mod that alters some methods from the source code, so Harmony is the way
