### ISSUE TITLE
Telekinesis can disable aiming for guns

### ISSUE THREAD

**Issue by Orkboyz** [studio-minus/madness-interactive-reloaded#215]
**Describe the bug**
Telekinesis can get stuck in its animation and force guns to shoot at the floor

**Steps to reproduce**
use Telekinesis multiple time in one scene

**Screenshots or video**

https://github.com/user-attachments/assets/fae9b2ef-f476-4a40-bc5c-630873d91d39

**Desktop**

 - OS: Windows
 - Version: 0.48.8

**Comment by mestiez** [comment]
Yes this was solved with #213
