### ISSUE TITLE
Crash ID Uwaas

### ISSUE THREAD

**Issue by Lumnyl** [studio-minus/madness-interactive-reloaded#224]
**Describe the bug**
"Program has stopped working" crash. Happened right after I restarted in the campaign room with the End Soldat.

**Screenshots or video**
![image](https://github.com/user-attachments/assets/c176cf2c-a75b-4508-8c97-dd7dcf5ac8af)
[mir_Uwaas_components.md](https://github.com/user-attachments/files/17002832/mir_Uwaas_components.md)
[mir_Uwaas_systems.md](https://github.com/user-attachments/files/17002833/mir_Uwaas_systems.md)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.49.0

**Comment by mestiez** [comment]
Same issue as #226
