### ISSUE TITLE
game still crashed while i was holding a weapon

### ISSUE THREAD

**Issue by M-goofy** [studio-minus/madness-interactive-reloaded#226]
**Describe the bug**
the game crashed while i was holding a weapon, basicly before i died while pressing E i grabbed a weapon while dead

**Screenshots or video**

![Screenshot (35)](https://github.com/user-attachments/assets/e314bb13-c1e3-43a8-bf4a-eedbb06e623a)

**Desktop (please complete the following information):**
 - OS: windows 11  64 bit
 - Version 0.49.0

**Comment by TeomanDeniz** [comment]
It's a bit hard to do it. But if you manage to get the gun **after** you die, this crash triggers.

https://github.com/user-attachments/assets/260f626c-ed5f-47c0-ae8f-3744db7dd577

**Comment by M-goofy** [comment]
> It's a bit hard to do it. But if you manage to get the gun **after** you die, this crash triggers.
> 
>  2024-09-14.19-46-28.mp4

ye thats how it crashed for me

**Comment by mestiez** [comment]
Fixed!

**Comment by M-goofy** [comment]
> Fixed!

very epic :)
