### ISSUE TITLE
Adding in an EnemySpawnSystem in LevelEditor will crash the game. I am unsure why.

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#227]
**Describe the bug**
Exactly what the title says.

**Steps to reproduce**
1. Open the absolutely mindbreaking level editor
2. Add a EnemySpawnSystem after tinkering with it for a while.
3. Crash.

**Expected behavior**
Not a crash?? I can't get enemies to spawn at all lol.

**Screenshots or video**
bug report
![image](https://github.com/user-attachments/assets/f04f10b5-5080-4ca0-9f62-bbf4d66b8808)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 0.49.0

**Additional context**
This level editor is so confusing

**Comment by SacredSven** [comment]
Oh, and I know it says "Duplicate" in the bug report. But I didn't spawn in a first one myself.

**Comment by mestiez** [comment]
That system should never be added to a level because it's always present.
