### ISSUE TITLE
Make game's default fonts replaceable with custom fonts

### ISSUE THREAD

**Issue by Krasapan** [studio-minus/madness-interactive-reloaded#242]
**Description**
Make game fonts replaceable with mods

**Reasoning**
At the moment it's not possible to replace [default fonts](https://github.com/studio-minus/madness-interactive-reloaded/blob/bdfda7911cc7b5be1f366e21772618570897aa2d/src/MadnessInteractiveReloaded/Assets/Fonts.cs#L16), because they are sealed with `public static readonly`, and they are loaded before any mods
It would be great to be able to have custom fonts and working locale mods

**Comment by mestiez** [comment]
forgot to address this issue.

theyre `public static AssetRef<Font>` now, so you could replace the asset with a mod.
