### ISSUE TITLE
Characters are attempting to retrieve a weapon that is out of bounds

### ISSUE THREAD

**Issue by Dikkiedink** [studio-minus/madness-interactive-reloaded#243]
**Describe the bug**
When a weapon lands in an inaccessible area, the AI characters will still attempt to retrieve it, leading to them walking endlessly into invisible barriers.

**Expected behavior**
Characters ought to cease their attempts to acquire a weapon located in an area that is out of reach.

**Screenshots or video**
![image](https://github.com/user-attachments/assets/577645aa-51e5-43d5-abc4-c2d60d6b959c)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.49.1.0

**Comment by Koofa** [comment]
bolo
