### ISSUE TITLE
Add crosshair

### ISSUE THREAD

**Issue by Koofa** [studio-minus/madness-interactive-reloaded#245]
**Description**
A crosshair which just functions as a fancy looking mouse.

**Reasoning**
Makes it easier to know where you're shooting, especially if you have a large screen.

**Additional context**
It could show the player the accuracy of the weapon they're currently holding or if they're out of ammo. It could also show if the npc you're hovering over is a friendly or an enemy.

**Comment by Krasapan** [comment]
ngl this game should have a crosshair option
for now there are only static and dynamic crosshair mods from the community in MIR discord
Orsoniks said he'd polish his dynamic crosshair mod and make a pull request, so maybe we will get a crosshair feature

**Comment by Krasapan** [comment]
Orsoniks can't make a pull request at the moment until he's back from the flooded region he's evacuated from. His crosshair will be a toggleable default feature in the main menu, so anyone please don't steal this job from him 🙏

**Comment by Orsoniks** [comment]
ill get on it when i can, i already have some basic code for it in place
