### ISSUE TITLE
Human Body Shield ( Add this please )

### ISSUE THREAD

**Issue by idontrizz** [studio-minus/madness-interactive-reloaded#246]
So what important about this cool feature that may be or not be added, Well it gonna protect us from incoming hostile projectile, So instead of eating bunch of bullet, Our dead opponent should eat the bullets right? We dont wanna get hurt anyways when killing enemy's proficiently and professionaly and maturely and aimbotelly

**Comment by Abs0lv3d0r** [comment]
I definitely agree with your opinion, it seems like an essential addition. a example of crowded levels like elevator or much better HELLevator section enemias start falling from both sides and are well equipped with many firearms for constant supressive fire, this mechanic will supress the fire the force of the wave and will grant you to regen tac-bar as long as they don´t attack you from back.
