### ISSUE TITLE
Corpses from a previous room still appearing in the next room

### ISSUE THREAD

**Issue by centa3456** [studio-minus/madness-interactive-reloaded#250]
![image](https://github.com/user-attachments/assets/8c049896-971d-4ef6-a6d7-e6e6dabbfded)
![image](https://github.com/user-attachments/assets/22e9b16e-b6a7-448b-b37e-01fffc5c5a70)

for some odd reason, (in specific levels), the corpses from a previous room will simply stay in the next room i enter

it only seems to happen when i enter a room that is the same size as a previous room, otherwise and none of that seems to happen

no idea why this happens

OS: Windows 10 64 bit
Version: 2H22

**Comment by mestiez** [comment]
Very likely related to #133

**Comment by E-the-Z** [comment]
I have a similar issue, but the bodies have a sort of checkerboard pattern, with transparent squares

**Comment by mestiez** [comment]
This kind of thing will be associated with #36 from now on
