### ISSUE TITLE
game simply does not open

### ISSUE THREAD

**Issue by maggain** [studio-minus/madness-interactive-reloaded#253]
**Describe the bug**
The game, no matter what is done, does not open.

**Steps to reproduce**
1. No clue, other people have also had this problem.

**Expected behavior**
Game opens.

**Screenshots or video**
Other people reporting same issue have showcased it

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Any

**Additional context**

**Comment by mestiez** [comment]
Just not enough information.

**Comment by bloodysnowlol** [comment]
you solve the problem?
