### ISSUE TITLE
Wanted poster doesnt reflect modded armor's texture rescale

### ISSUE THREAD

**Issue by BlackRifleCrono** [studio-minus/madness-interactive-reloaded#262]
When using custom armor, if the armor had been scaled, it'll look very off in the wanted posters, its not really much more than that, and would be nice to be fixed.

This has been on all versions to my knowledge

You can see what my guy looks like, and the messed up accessories in the posters
![Screenshot (348)](https://github.com/user-attachments/assets/0eb82050-f106-47c7-a31c-b0bc9b5c2ab9)

**Comment by BlackRifleCrono** [comment]
i know this is not new, but still should be fixed

**Comment by mestiez** [comment]
this is because the `ThumbnailRenderer` doesn't take scaling into account. Should be easy to fix.
