### ISSUE TITLE
lvl_ladder climbing animation has the wrong target

### ISSUE THREAD

**Issue by Koofa** [studio-minus/madness-interactive-reloaded#264]
**Describe the bug**
lvl_ladder climbing has its target set to "nearest" instead of "player"

**Comment by dch-GH** [comment]
![image](https://github.com/user-attachments/assets/9ff7ea08-0a91-4dd6-872c-9afbb93a2a00)
I think changing this from Nearest -> Player would fix the problem?

**Comment by LatteImACheater** [comment]
I think its supposed to be like that no???

**Comment by Koofa** [comment]
huh? oh
