### ISSUE TITLE
Tutorial should clearly end after killing 12+ Enemies.

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#267]
**Description**
I noticed that the final level of the tutorial goes on forever, I believe that it should end by itself after 12 or more enemies are killed.

**Reasoning**
This may be confusing for New Players that don't know they have to exit, and could cause bug reports to roll in for something that isn't a bug. You could also add an enemy counter in the top right to also introduce the enemy counter to new players as a mechanic. This could help with getting them familiar with the game!

**Additional context**
I was confused myself when I was playing it, lol. It also doesn't mention the Middle Mouse Button being to stun enemies with the current weapon, or to stab them.

**Comment by mestiez** [comment]
It stops when you parry and kill the enemy...

**Comment by SacredSven** [comment]
> It stops when you parry and kill the enemy...

I went on for 8 minutes. 8 minutes without it ending. How? I'm pretty sure I parried an enemy and then killed them multiple times.

**Comment by Orsoniks** [comment]
no it definitely ends the moment you parry an enemy
