### ISSUE TITLE
Zombies update

### ISSUE THREAD

**Issue by Balage0429** [studio-minus/madness-interactive-reloaded#268]
**Description**
Make zombies like in Madness Project Nexus Classic

**Reasoning**
It would have a more madness feeling

**Comment by Orsoniks** [comment]
elaborate

**Comment by Balage0429** [comment]
> elaborate

awwwh :<

**Comment by Orsoniks** [comment]
how descriptive!

**Comment by Balage0429** [comment]
> how descriptive!

Fr.

**Comment by Balage0429** [comment]
> how descriptive!

I think it should be like , the zombies can only do melee attack and they should have an own melee animation.

**Comment by Balage0429** [comment]
> zombies

I

> > how descriptive!
> 
> I think it should be like , the zombies can only do melee attack and they should have an own melee animation.

And own walking animation too
