### ISSUE TITLE
Player Character Jitters When Choosing Campaign.

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#271]
**Describe the bug**
Exactly what the title says, the character freaks out between choosing campaigns.

**Steps to reproduce**
1. Go to Campaigns.
2. Select between them.
3. Cry after seeing everything go wrong.

**Expected behavior**
Not to see jittering..?

**Screenshots or video**
https://youtu.be/lz5uHTB932E

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.49.1

**Additional context**
This is probably easy to fix.

**Comment by dch-GH** [comment]
Can't recreate this. Could be a mod issue?

**Comment by SacredSven** [comment]
> Can't recreate this. Could be a mod issue?

I'll send a list of my mods when I get home, I'm unsure if its an issue but you can look through them to find out. I guess. Odd Issue, though.
