### ISSUE TITLE
Where TF is the GOREE

### ISSUE THREAD

**Issue by Abs0lv3d0r** [studio-minus/madness-interactive-reloaded#279]
It is simple, after all these patches i never seen some good ´ol chunk of blood(only in the walls) or Entry wounds, in this patch appeared red and yellow lines but not a wound. i heard from someone that gore depends on my hardware. i want this solved on future patches or at least give me a good excuse of why is this only happening to me (or it´s not just me). i wanna hear any replies.

**Comment by LatteImACheater** [comment]
you might wanna get an intel laptop

**Comment by Abs0lv3d0r** [comment]
hey, how did you know that i got one? and the fact that im too POOR to have a better laptop?

**Comment by mestiez** [comment]
Duplicate of #54
