### ISSUE TITLE
Rich has wrong gore texture

### ISSUE THREAD

**Issue by E-the-Z** [studio-minus/madness-interactive-reloaded#280]
**Describe the bug**
After blasting Rich's outer layer away with an automatic shotgun, the gore texture for a regular unit (agent, grunt, machinist) shows instead of Rich's usual texture.
**Steps to reproduce**
Not entirely sure why it displayed this texture this time, it usually displays correctly
1. Equip FLCL and (preferrably) HP improbability disks
2. Equip Saiga-12 or USAS-12
3. Rapidly fire at Rich
4. Watch the wrong texture (maybe?) show through

**Expected behavior**
Rich to have the correct gore texture, and for his teeth to line up

**Screenshots or video**
![image](https://github.com/user-attachments/assets/03f0abc9-9f55-4704-be86-9d677f3f7e3f)
Not the best screenshot, but the only one I could get

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.49.1

Also just noticed the missing slide on his automag as well

**Comment by mestiez** [comment]
weirdly enough this fixed itself
