### ISSUE TITLE
[Modding] - More Sound Effect Customization

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#284]
**Description**
I believe that we should be able to custom gun sounds more, like the shotgun pump sound. Or maybe even the sounds that play when you're running out of ammo/ran out of ammo.

**Reasoning**
This could allow modded guns to be more creative and possibly make for sense (Alien Weapons, for example.) As well as making it generally easy on the Dev side to make them able to pick from any sound. This may make it easier to just make guns in general.

**Additional context**
Please add this, If it's already in the game................................ Bruh

**Comment by SacredSven** [comment]
QUICK ADDITION (FAILSAFE): If there is no custom gun sound selected, default to normal gun sounds.

**Comment by SacredSven** [comment]
Turns out: I'm stupid. This all exists already. But apparently its too damn hard for some people to figure out. Lol

**Comment by InputSoldatcc** [comment]
We've all been there
