### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Balage0429** [studio-minus/madness-interactive-reloaded#286]
Thanks studio minus for making this game. I love it, even tho its unfinished. Thank you all so much. Keep up the good work! I wish you all luck for the future!

-Bazsi

**Comment by LatteImACheater** [comment]
rahhhhh

**Comment by InputSoldatcc** [comment]
Dude

**Comment by Balage0429** [comment]
> Dude

what?

**Comment by Abs0lv3d0r** [comment]
YAAAYY

**Comment by InputSoldatcc** [comment]
Expected

**Comment by Balage0429** [comment]
> Expected

😔
