### ISSUE TITLE
About boss atk

### ISSUE THREAD

**Issue by TestGGA-Normal** [studio-minus/madness-interactive-reloaded#287]
**Describe the bug**
While using Sword boss have icon of using pistol to aim as player when boss doesn't use pistol
**Steps to reproduce**
1. Dunno how

**Expected behavior**
while using sword if you move out of his range nearly out of the screen he will start to use this atk you still can see him on the screen
**Screenshots or video**
don't have because cannot pause in mid game to have screenshot

**Desktop (please complete the following information):**
 - OS: [Windows or Linux?] Window 10 Pro
 - Version [e.g. 0.48.3]

**Additional context**
just miss lead to some unfair died that all :D

**Comment by InputSoldatcc** [comment]
Im pretty sure thats not a bug he is just hitting you with the bottom of the gun

**Comment by mestiez** [comment]
I have no idea wtf this means!!!

**Comment by TestGGA-Normal** [comment]
> Im pretty sure thats not a bug he is just hitting you with the bottom of the gun unless youre talking about something else

No he was using the sword and im stand far away

**Comment by TestGGA-Normal** [comment]
> I have no idea wtf this means!!!

I will make it simple He have target mark while using Sword and I dunno wat trigger it
