### ISSUE TITLE
Realistic Gore Mode

### ISSUE THREAD

**Issue by iternetidiot** [studio-minus/madness-interactive-reloaded#294]
**Description**
Add an optional mode of the game that has more in-depth and realistic gore and wounding, such as bruises, caved-in skulls, skin tearing, more "real" gore and dissection/decapitation

**Reasoning**
I've seen multiple people asking for more "realistic" gore in the game, and a switch or slider to toggle Realistic/NSFW gore on or off would be a good solution.

**Additional context**
I'd completely understand if this isn't worth the effort, as it is a very big ask, and may not work with the style of the game.

**Comment by ahmetboi** [comment]
That would look metal

**Comment by Abs0lv3d0r** [comment]
something like C N gore animations? cool.

**Comment by cricketboy01** [comment]
Kinda like the old people playground thing that got removed?
