### ISSUE TITLE
Some basic issues I found (and a bug but I can't choose both)

### ISSUE THREAD

**Issue by cricketboy01** [studio-minus/madness-interactive-reloaded#295]
These are some things I noticed about the game that would probably improve it if fixed, though are very small in nature. under the paragraph is a bug.

1: The corpses lean against walls when they die, and due to how fast they stamp against the bg they will just sit there. While active they also block bullets, preventing you from hitting enemies at the doorway.
2: blunt weapons feel a bit weak to play with (I'm not sure weak is the right word) since they leave no mark on enemies, I feel like it would highly increase immersion if they left a bruise or marking of some kind upon enemies when they hit them.
3: Weapon physics are a bit odd in the sense that when they hit the floor, seeing as they snap into place which just feels odd to me.
4: The hand pumping the big shotgun is really far away from the body.
5: (edited in from here) The body or equipment of enemies can float while there is nothing below them (example: engineer or machinist facial gear floats when a shotgun blast removes most of their face) which can look really weird. This also goes for parts of the body. (EDIT: this also can happen with agent glasses, despite them normally flying off of the face of the agent.)
6: Gunshot wounds can be layered under the player's clothing, which looks off.
7: thrown bladed weapons may float on enemies that they are embedded in, example being an agent that had a sword hovering close to its head after it was thrown into said agents head.

I would like to emphasize that these are nitpicks and shouldn't be taken too seriously.

A bug I'd like to report is to do with experiment.
While I was playing experiment mode, I had auto spawn on with agents, engineers, grunts and soldats armed with guns, though previously they had melee weapons and there where quite a few on the floor. I was in the room to the right of the main room and for some reason, the door to the party room was stuck open and wouldn't let me through. Clearing the map did not help. I don't know how this happened, there wasn't an enemy or item stuck there (seeing as it didn't stop even after clearing the map) so I'm not sure what it is.

**Comment by mestiez** [comment]
please don't group these. make an issue for each bug and each suggestion

**Comment by cricketboy01** [comment]
> please don't group these. make an issue for each bug and each suggestion next time

My bad, I was writing down the paragraph while playing and didn't want to submit a bunch in case that would be spamming or annoying
