### ISSUE TITLE
No bullet decals on game

### ISSUE THREAD

**Issue by pmbsaa** [studio-minus/madness-interactive-reloaded#309]
**Describe the bug**
Gore bug

**Steps to reproduce**
1. opensgamr
2. shoots guy
3. has no blood gore
4. only blood lines that's it

**Expected behavior**
can't have bullet gores 😔 

not have screenshot yet but yeah

Laptop
 - OS: [Windows 11 (PRO)]
 - Version [e.g. 0.49.1-beta]

**Additional context**

**Comment by mestiez** [comment]
Duplicate of #54
