### ISSUE TITLE
Add a disk logger to the ILogger thing

### ISSUE THREAD

**Issue by mestiez** [studio-minus/madness-interactive-reloaded#31]
**Description**
The crash reported needs a disk log to work properly.

**Comment by dch-GH** [comment]
What do you mean by disk log? Like, the InstabilityDisks? I assume you're talking about: https://github.com/studio-minus/madness-interactive-reloaded/blob/af672a1859080fd97ddda8ba33011451d97cf61a/src/MadnessInteractiveReloaded/Program.cs#L63-L69

**Comment by dch-GH** [comment]
I have made a lapse in judgement from being tired. I know what you mean now. This will be fixed ASAP.

**Comment by dch-GH** [comment]
Depends on: https://github.com/mestiez/Walgelijk/pull/21
