### ISSUE TITLE
Skeleton color does not match character blood color

### ISSUE THREAD

**Issue by dominikrni** [studio-minus/madness-interactive-reloaded#314]
**Describe the bug**
A character i've created has blood color set to black, but when it gets to the skeleton , it is shown to have a yellow one instead of a black one as expected. As well as that, some parts of the blood also seem to be yellow.

**Steps to reproduce**
1. Have a character with the blood color set to like a dark color (for example: black)
2. Take a weapon of your choice
3. Shoot character until the skeleton is shown

I am not sure if it'll be reproduced perfectly, but ill attach an example character just in case the steps above do not work

**Expected behavior**
What was supposed to happen is that the character's skeleton color is supposed to match the color of the blood (for example: if the character has black blood, it would have a black skeleton)

**Screenshots or video**
![image](https://github.com/user-attachments/assets/987607ae-d295-4dfc-b505-4ec6d4fb60fb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.49.3-beta

**Additional context**
Here is the character look file that brought my attention to this in the first place: 
[characterlook.zip](https://github.com/user-attachments/files/17208374/characterlook.zip)

Also, the blood color used for said character is #131205, whose hue would be yellow under HSL in that case. I don't know if that will help, but might have something to do with it?

**Comment by mestiez** [comment]
this happens because only the hue is considered when colouring the underlying gore texture.
the solution is to also apply the saturation

**Comment by mestiez** [comment]
![image](https://github.com/user-attachments/assets/1dac6db0-451d-44a7-9e61-3d3b0bf32fde)
