### ISSUE TITLE
Skeleton and rest of the gore layer is now just a flesh blob

### ISSUE THREAD

**Issue by miteMellow** [studio-minus/madness-interactive-reloaded#316]
**Describe the bug**
The fix for #314 has from what I presume "broken" the gore layer, as they now are detailess without any bones or nerves like previously.

**Steps to reproduce**
1. Shoot an enemy and see the gore on it's layer

**Expected behavior**
Be able to see to see the detail on the gore layer like ribs, teeth, etc.

**Screenshots or video**
![solidgorelayer](https://github.com/user-attachments/assets/848c88fa-245b-4d3e-8226-d17c8bc8be09)
![fleshblob](https://github.com/user-attachments/assets/e4f1a8c1-736c-4432-9420-9c329b7fe2a6)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 22H2

**Additional context**
I presume it might be because of saturation now being applied to the layer. I'm not a coder so my suggestion could be wrong but maybe making the gore layer grayscale then adding a color filter of the color of the blood the player chooses could fix it? Maybe also adding it so that when its the specific normal red (#ff0000) /yellow blood (#ffe600) color code it uses the original gore layer image to preserve its looks.

**Comment by mestiez** [comment]
yeah i was made aware of this recently. ill fix it right meow
