### ISSUE TITLE
Game crashes trying to load campaign after completion

### ISSUE THREAD

**Issue by EaTStu** [studio-minus/madness-interactive-reloaded#323]
**Describe the bug**
Upon beating the primary campaign or tutorial, load the same thing again and it will crash. When this first happened to me, I thought it was the grunt disk causing it. Hence, me showing the drive was equipped. I only guessed that it was just the campaign alone after looking at the error closely, and trying a separate level.

**Steps to reproduce**
1. Install and then run game.
2. Complete campaign/tutorial all in one go
3. Play it again
4. Profit

**Expected behavior**
I expected the campaign/tutorial to restart, or replay the last level. Unfortunately, I had to manually select a level in order for it to continue.

**Screenshots or video**

https://github.com/user-attachments/assets/c1df695f-05eb-47ab-b957-f532eb59f6c6

**Desktop (please complete the following information):**
 - OS: 64-bit Windows 10 Pro, Version 22H2 Build 19045.4894
 - Version Version 0_49_4

**Additional context**
I tried this twice, one in an nVME drive and one with a HDD. I think what's going on here is it's trying to load level 43/42, which doesn't exist, causing the game to panic and crash.

**Comment by mestiez** [comment]
fixed :)
