### ISSUE TITLE
Nerf A.T.P. Soldat or add a difficulty setting

### ISSUE THREAD

**Issue by KebabKiller420** [studio-minus/madness-interactive-reloaded#331]
Let's face it, the game is great.  But these guys break the illusion of  being tanky. They  even hide behind other enemies so you can't kill them before it's too late. I get it, the madness games are supposed to be difficult but  I  just want a little  bit action. Nothing that makes the  game unplayable. So, Please either nerf their  lock on mechanic or just add a difficulty setting. Please

**Comment by miteMellow** [comment]
You can jump (to dodge) or hold right click [to parry with meele (with the exception of shotguns, you can't parry those I think?)] right before the red target closes on you and if they dodge your bullets you can wait until they finish their dodge animation to shoot then again and kill them. You get used to it later on.

**Comment by mestiez** [comment]
![27_september_2024](https://github.com/user-attachments/assets/561eb44a-9102-4e04-ad8a-4a4085d3cedb)

**Comment by KebabKiller420** [comment]
> ![27_september_2024](https://private-user-images.githubusercontent.com/32131519/373942763-561eb44a-9102-4e04-ad8a-4a4085d3cedb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjIxOTMsIm5iZiI6MTcyODIyMTg5MywicGF0aCI6Ii8zMjEzMTUxOS8zNzM5NDI3NjMtNTYxZWI0NGEtOTEwMi00ZTA0LWFkOGEtNGE0MDg1ZDNjZWRiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEzMzgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxOWVjYWQ0OWI0ZmM5MWRiNGUwMzJkNDNjMjc0ZDk5NWZkM2VjOTk4NTBmMzNmNTczOTFhZWE4ZTAxZmRhZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lN8LTankrX_laj7wy4QO5Qc_M0RyJZl6U0iDhdm4GOE)

I'm not even insulting the game. So don't be a dick

**Comment by KebabKiller420** [comment]
Also, why is a difficulty setting off the table? OG Project Nexus had it and it was great

**Comment by InputSoldatcc** [comment]
add a tourist mode and a director phobos character that insults you for playing in tourist mode
