### ISSUE TITLE
Pressing "Continue" on the campaign "Employee of the Month" after completion crashes the game

### ISSUE THREAD

**Issue by FrostyTheHobo** [studio-minus/madness-interactive-reloaded#332]
After completing the campaign, the game level is still set as the last one (42/42). Pressing continue crashes the game.

I'm playing on version 0.49.4.0, on Windows 11.

It happens even without any Incompatibility Disks equipped.

I've attached a screenshot of the error message, which opens in the browser.
![asdasf](https://github.com/user-attachments/assets/ccd1d692-28c0-4ebc-a523-2a51c6ac8b65)

**Comment by issueacc** [comment]
ive had a similar issue, but after rewatching the final cutscene it gave me 43/42 with around the same error (index was outside the bounds of the array)
