### ISSUE TITLE
I was playing literally just now, then my game crashed out of nowhere, and I can't open the game anymore, Is it a game problem or was there a new version release?

### ISSUE THREAD

**Issue by godenispro** [studio-minus/madness-interactive-reloaded#333]
**Describe the bug**

**Steps to reproduce**
1. ...

**Expected behavior**

**Screenshots or video**
If applicable, add media to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [Windows or Linux?]
 - Version [e.g. 0.48.3]

**Additional context**

**Comment by Dikkiedink** [comment]
Kindly fill in the bug report template before posting things like this. This is too vague. What were you doing before it crashed?

**Comment by godenispro** [comment]
> Kindly fill in the bug report template before posting things like this. This is too vague. What were you doing before it crashed?

I simply clicked on "Continue game" thingy and then it crashed
