### ISSUE TITLE
Extend customization to feet

### ISSUE THREAD

**Issue by knockedforsix** [studio-minus/madness-interactive-reloaded#337]
**Description**
Allows for foot customization like the other parts. Just a png of whatever shoe and it'll be done.

**Reasoning**
Given how it's the only part unable to be customized, it'll be sick to see it be done, and would probably save a future headache involving characters like the Auditor.

**Comment by mestiez** [comment]
Added by 7122868. Although there's no button for it in the customisation menu, it can be set in the `.look` file like so:

```
0.49.5

body
   default_body
   rocky_deimos_over

head
   masked_head
   welding_mask_eyes

feet textures/bodies/default/foot-black.png
blood #FF0000FF
```

Unlike the others, it's just a direct reference to a texture because of how simple it is.
