### ISSUE TITLE
mod browser

### ISSUE THREAD

**Issue by issueacc** [studio-minus/madness-interactive-reloaded#338]
**Description**
sort of like how other games do it (like skyrim and fallout on console), there's a mod browser where you can quickly install mods without getting to the gamebanana page.

**Reasoning**
it'd be more useful to download mods in bulk with this rather than extracting a bunch of zip files.

**Comment by Purlime** [comment]
i dont even go to gamebanana

**Comment by mestiez** [comment]
cant do this because we dont have a place (of our own) to store mods
