### ISSUE TITLE
Hand system 'closer' to the original MI

### ISSUE THREAD

**Issue by Cboyjet4** [studio-minus/madness-interactive-reloaded#343]
**Description**
I probably couldn't fit the whole thing in a long suggestion, so I made a YouTube video demonstrating it.
Basically, it changes the hand system to involve more movement with the mouse, instead of just pre-set animations, similar to the original madness interactive. I didn't take into account skill levels or anything so that's on me lol.

https://www.youtube.com/watch?v=4wyZWNo88QA

I think something was lost in translation between the original MI and this version, the combat in MIR is really boring in my opinion and all you do is click until they fall over, I think something like this could add just a tinge more engagement to melee combat.

**Reasoning**
I felt the game lost some of it's depth and charm with the removal of the old system, so I came up with this, it would probably be shit difficult to implement something like this this late anyways lol.

**Additional context**
Perhaps it could be an option or improbability disk if implemented idk

**Comment by Mael480** [comment]
Would be insane if it got added

**Comment by issueacc** [comment]
i would love this

**Comment by mestiez** [comment]
At this point in development, such a large and fundamental change should not (and probably cannot) be implemented. Besides, it doesn't fit any other gameplay element or any part of the game design.

Neat video though!! Maybe someone could implement this as a disk.

**Comment by AlmaTray** [comment]
> At this point in development, such a large and fundamental change should not (and probably cannot) be implemented. Besides, it doesn't fit any other gameplay element or any part of the game design.
> 
> Neat video though!! Maybe someone could implement this as a disk.

is it actually possible? like, wouldn't the engine snap from such a fundamental mod? :D
