### ISSUE TITLE
The ability to animate the scale of an object in an .anim file

### ISSUE THREAD

**Issue by Koofa** [studio-minus/madness-interactive-reloaded#346]
**Description**
The ability to change the scale of a limb in the `.anim` file to create smear frames.
Also, if this is implemented, the scale of the hands will need to be animated for the melee animations.

**Reasoning**
More accurate to the Madness Combat animations, especially for melee. It also looks better, obviously >:(

**Additional context**
Doe het erin NU @mestiez

**Comment by mestiez** [comment]
![image](https://github.com/user-attachments/assets/0732f990-73b7-4b03-8b3c-571f5e83a097)

![image](https://github.com/user-attachments/assets/e07338a4-469f-49b6-acb5-1454e9c1be89)

**Comment by Koofa** [comment]
Laaap!!!

**Comment by mestiez** [comment]
Some issues with my draft implementation:
- May interfere with 003 Disk deformation
- Occasional redundant transformation matrix calculation
- Occasional redundant `GetComponent` invocations (because clothes must match parent)
- `scale(1,1)` syntax is bulky

**Comment by SacredSven** [comment]
I feel like a little blur effect could be introduced too to make it even more "smear-ish" if that makes sense. I'm unsure how it would be done, and it would likely beat framerate up like Sanford in MC12. Alternatively, maybe it slightly fades at each edge of the hand for a better effect at less of a performance cost. I'm not a dev though, I'm an animator, and equally worse: 15 years old.. So if Wagelelik blows up trying to do this, sorry much.
