### ISSUE TITLE
Autospawn in experiment mode does not work

### ISSUE THREAD

**Issue by matness162** [studio-minus/madness-interactive-reloaded#347]
autospawn in experiment mode does not work

**Steps to reproduce**
1. enter experiment mode
2. tick autospawn box
3. nothing happens
4. type autospawn into console
5. error is given
![autospawn](https://github.com/user-attachments/assets/45107442-fbb0-4421-b389-9772b2b455ef)

 - OS: Windows 10
 - Version 0.49.4

**Comment by mestiez** [comment]
As the error says, you need to provide an argument:
`autospawn true` or `autospawn false`

**Comment by mestiez** [comment]
If you want to enable autospawning in experiment mode, you should assign characters by right clicking them in the NPC menu. As of now, this system is _very_ unintuitive.
