### ISSUE TITLE
this gore issue that i have had enough with

### ISSUE THREAD

**Issue by WholeDarkTris** [studio-minus/madness-interactive-reloaded#351]
![image_2024-10-18_195508496](https://github.com/user-attachments/assets/5c0e7d88-b28e-4cc5-afac-2813fd6e4002)
this is happening on my pc ever since i first downloaded the game, i am very desperate for a fix and i just wanna know if there is anything i can do.

**Comment by mestiez** [comment]
Duplicate of #263
