### ISSUE TITLE
Custom NPCs Not Working/Showing up in Experiment mode

### ISSUE THREAD

**Issue by knockedforsix** [studio-minus/madness-interactive-reloaded#352]
**Describe the bug**
For some strange reason, any mod built with the latest version will not have any custom mod NPCs working at all. Won't show up in Experiment mode, nothing. Doesn't matter if it has custom parts or not or if everything is set up correctly, it simply won't.

The only exception to this would be mod NPCs from mods made prior to the latest version.

**Steps to reproduce**
1. Make a mod with the latest version
2. Build an NPC to the correct specifications (Or take one for the source code)
3. Build mod
4: Watch as the NPC doesn't show up at all in Experiment mode (Works fine in the level editor as there's no presets)

**Expected behavior**
For custom NPCs to show up regardless.

**Screenshots or video**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.49.4

**Additional context**

**Comment by mestiez** [comment]
what do you mean by "Build an NPC"

**Comment by knockedforsix** [comment]
> what do you mean by "Build an NPC"

I meant making a .preset & .look file (+ .stat if it requires), then putting it into the mod folder in their respective folders.

**Comment by mestiez** [comment]
What are the respective folders?
