### ISSUE TITLE
No files should be written to the game's folder

### ISSUE THREAD

**Issue by Technochips** [studio-minus/madness-interactive-reloaded#358]
As far as I can tell, the game saves everything (log files, save files, mods, etc.) inside the game's directory. This tends to be pretty fine for locally installed Windows games. However, this has a few issues:

- This assumes the user has write permission in the game's folder. This is a nightmare when packaging for Linux.
- If there's one single install, every user on the computer shares the same data. The game assumes there's one install per user.
- When you update the game, maybe you don't want to accidentally erase your data?

This feature would just be to add the ability to read and write user data in the user's actual data directory:
* `%APPDATA%` on Windows
* `~/.local/share/` on Linux

This would make packaging on Linux possible.

**Comment by mestiez** [comment]
If this is implemented there should also be some kind of migration function.

**Comment by Technochips** [comment]
Slight research:
* You can use `System.Environment.SpecialFolder.LocalApplicationData` as a crossplatform way to get the folder.
* Log files are hardcoded in Walgelijk to be saved at `{executable file location}\logs` (in fact that causes a slight issue on Linux where it literally creates an empty `\logs` folder and then writes log files outside that folder which starts with `\logs\` (yeah with the backslash)). Walgelijk needs to be patched to account for this. Otherwise, it causes a crash when running in a write-restricted directory.

**Comment by mestiez** [comment]
(⌒‿⌒)
