### ISSUE TITLE
build.

### ISSUE THREAD

**Issue by Balage0429** [studio-minus/madness-interactive-reloaded#362]
the new blog said i can change the build to dev. how the hell can i do that? i tried multiple things but i couldnt. i tried to go to actions and try to build but as it seems i dont have permission.
![Képernyőfelvétel (2471)](https://github.com/user-attachments/assets/0934237b-6f49-4ec8-8139-78ec867be81d)
![Képernyőfelvétel (2470)](https://github.com/user-attachments/assets/ee26e771-5d84-47b0-98e5-03df56843d0f)

pretty pretty please help me 🥺

**Comment by mestiez** [comment]
sorry, but this is not a support forum

**Comment by mestiez** [comment]
read the README.md:

https://github.com/studio-minus/madness-interactive-reloaded#building-the-game

**Comment by Balage0429** [comment]
> sorry, but this is not a support forum

Alright! Sorry!
