### ISSUE TITLE
`lvl_roof_1` and `2`  have a black background and it keeps crashing

### ISSUE THREAD

**Issue by ahmetboi** [studio-minus/madness-interactive-reloaded#37]
im using a windows 11 64 bit,

![image](https://github.com/user-attachments/assets/a424c471-94cc-4a57-85c8-9872688caaa3)
also this happens

**Comment by mestiez** [comment]
Possibly related to #36

**Comment by ahmetboi** [comment]
probably

**Comment by betalambda** [comment]
I am having the same issue here over at #42

**Comment by Jayman812** [comment]
Will this ever get fixed im having same issue

**Comment by mestiez** [comment]
I think this was fixed
