### ISSUE TITLE
Crash when selecting Employee Of The Month

### ISSUE THREAD

**Issue by SacredSven** [studio-minus/madness-interactive-reloaded#370]
**Describe the bug**
Every campaign works but Employee Of The Month is like the cousin at thanksgiving everyone hates, and decided to shit itself.
Every time I pressed it, CRASH! And an identical Crash Report. From what I can tell, it can't figure the hell out how to handle the fact a Campaign Stats Entry exists (odd) and it freaks out. Why? It's for you devs to scream at me about, idk.

**Steps to reproduce**
I literally do not know how to reproduce. This wasn't happening before.

**Expected behavior**
For it to.. uh.. not crash?

**Screenshots or video**
![Screenshot 2024-11-16 at 17-34-12 Madness Interactive Reloaded has crashed](https://github.com/user-attachments/assets/3f70bdbd-7f65-4792-a47d-6009b441f403)
https://youtu.be/dCZa4sWGV80

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: 0.50.0

**Additional context**
If I sound absolutely done in the video, its because i had it crash on me like 8 times. Took alot of strength to not scream during the video.

**Comment by mestiez** [comment]
You have two billion mods so the exact cause of this is hard to figure out, but the exception is clear: your employee_of_the_month stats file is malformed. It exists, but has been skipped during registration. If you share the file here, I can tell what happened. Until then, the solution is to delete it. The path is given in the exception.

**Comment by SacredSven** [comment]
Update: I figured it out. The file was empty, for some unknown reason. Deleting it allowed the game generate a new one, and fixed the crash. This seems to be the fix for most malformed stats files.
