### ISSUE TITLE
Cannot build from new AppData mod folder

### ISSUE THREAD

**Issue by betalambda** [studio-minus/madness-interactive-reloaded#378]
**Describe the bug**
It is currently impossible to build from the new mods folder in the AppData folder. In order to build and test mods, you mod must be in the old mod folder in the MIR game files to build the mod, and it must be taken to the new mod folder for it to be usable in the game.

Doing this "move back and forth from the mod folders" repeatedly is very annoying, and I don't think the disks are gonna like the constant moving around :P

**Steps to reproduce**
1. Try to build from the new mod folder location in AppData
2. Build Fail, MIR not found
3. Try to build from the old mod folder in the MIR game files
4. Build Success.
5. Try to run the game.
6. Mod does not show up since it is not in the new mod folder.

**Expected behavior**
The game, or at least the mod template, considers the new mod folder as a valid place to build the mod.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.50.0

**Additional context**
I do not know if it's feasable to allow building from anywhere outside the MIR game files since it's more of a Visual Studio thing or smthing, but it would be appreciated if it was possible to at least manually define the locations for the required files the mod needs to read in order to build, rather than the template expecting it to be in the same place as the files.

**Comment by mestiez** [comment]
The old mod folder should still be a functional place to put mods...

**Comment by betalambda** [comment]
last time i tried to use the old mod folder, it did not read the mod.

let me try dragging my mod back into the old mod folder and see if the game still reads it.

**Comment by betalambda** [comment]
ok NOW it reads from the old mod folder, and read it first (rblx-yter is the mod in question)
![image](https://github.com/user-attachments/assets/6e5e5735-c236-4fcb-8f92-cb9ae0f941b2)

i'll keep poking and prodding with this to see if my issue was just a freak incident

**Comment by betalambda** [comment]
apparently the old mod folder DOES work. i managed to create a mod from scratch from there. idk what happened that time, probably something to do with .dlls XD
