### ISSUE TITLE
missing hands

### ISSUE THREAD

**Issue by leycarnet** [studio-minus/madness-interactive-reloaded#51]
missing hands in menu in campaign in experiment mode
both me and enemies missing hands except for campaign mode they sometimes have 1 arm

![image](https://github.com/user-attachments/assets/a3426f98-936f-47ee-a6d5-9562ada1078e)

![image](https://github.com/user-attachments/assets/5f43897f-2853-4c72-96e5-0601a33928f3)

unable to fight and get any damage at all
when spawning weapons they dissapear once hit the ground but still pickable
able to shoot with guns but not doing any damage

crashing when reviving

- GPU: GTX 1050
 - OS: Windows
 - Version 0.48.3

**Comment by mestiez** [comment]
Duplicate of #38

**Comment by CHELOBAS** [comment]
just what should i do to solve the problem
