### ISSUE TITLE
2 levels are broken

### ISSUE THREAD

**Issue by MoshaelMosscreep** [studio-minus/madness-interactive-reloaded#52]
There 2 broken levels in the "Employee of the Month" campaign. The "lvl_roof1" and the "lvl_cutscene_bossbattle"
![image](https://github.com/user-attachments/assets/9ee4569d-f3a1-4ac4-9225-75347c576462) (Cyn not included)

"lvl_roof1" has the wrong BG (as it probably uses the one from the experiment map), enemies left counter is gone and crashes after completion.
"lvl_cutscene_bossbattle" is probably the reason the previously mentioned level crashes.

**Comment by MoshaelMosscreep** [comment]
Update: apparently it's just the 2 roof levels, not the cutscene levels. Though lvl_roof2 has a bg but crashes after well... y'know, completion

**Comment by Koofa** [comment]
Is this similar to #37? If so the issue has already been reported

**Comment by mestiez** [comment]
Unsure what this issue was but nothing similar has been reported recently.
