### ISSUE TITLE
Pressing Escape immediately after dying crashes the game

### ISSUE THREAD

**Issue by ThatExplo** [studio-minus/madness-interactive-reloaded#58]
**Describe the bug**
Pressing Escape immediately after dying crashes the game

**Steps to reproduce**
1. Die
2. Immediately pause
3. CrashLog

**Expected behavior**
Well, I'd expect it to pause the game obviously.

**Screenshots or video**
https://github.com/user-attachments/assets/991ed747-5c69-495e-a89e-73ad5b4a55f3

**Desktop:**
 - OS: Windows
 - Version 0.48.3

**Comment by mestiez** [comment]
Duplicate of #37
