### ISSUE TITLE
Disk progress should be saved more frequently

### ISSUE THREAD

**Issue by ahmetboi** [studio-minus/madness-interactive-reloaded#60]
**Describe the bug**
I collectded some of them, i check it,no disks
**Steps to reproduce**
1. play the game and find disks
2.check the menu
3.no disks
**Expected behavior**
Disk should appear in the menu

**Desktop 
 - OS: windows
 - Version [e.g. 0.48.3]

**Comment by mestiez** [comment]
This happens because the game closed improperly. Disk progress should be saved more frequently.
