### ISSUE TITLE
Mouse lock

### ISSUE THREAD

**Issue by mestiez** [studio-minus/madness-interactive-reloaded#62]
**Description**
The cursor should be locked in the window if the game is set to fullscreen

**Reasoning**
It is expected fullscreen behaviour

**Comment by dch-GH** [comment]
Depends on: https://github.com/mestiez/Walgelijk/pull/20

**Comment by SuperGamersGames** [comment]
Ditto this. I've clicked out of the window more times than I intend to. 😅
