### ISSUE TITLE
Saviour and telekinesis disks should give the player the abilty to use it on spawned background weapons

### ISSUE THREAD

**Issue by AlmaTray** [studio-minus/madness-interactive-reloaded#69]
**Describe the bug**
Jebus cannot pick up naturally spawned (background) weapons with TK

**Steps to reproduce**
1. just try it

**Expected behavior**
the weapon should have floated up in the air

**Screenshots or video**
![image](https://github.com/user-attachments/assets/95aa5760-11c9-440a-912e-ee70ad67a55a)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Version 0.48.4

**Comment by Koofa** [comment]
Not really a bug, this is a feature request right?
