### ISSUE TITLE
Fullscreen and pressing the load button in the level editor crashes the game

### ISSUE THREAD

**Issue by Koofa** [studio-minus/madness-interactive-reloaded#71]
**Describe the bug**
When fullscreen is enable and the load button in the level editor is pressed, the game crashes or stops responding

**Steps to reproduce**
1. Make the game fullscreen
2. Open the level editor
3. Press the "load" button

**Expected behavior**
The game needs to exist fullscreen and open windows explorer

**Comment by dch-GH** [comment]
What seems to be happening is that the file dialog is just opening and displaying behind the game, if you have a secondary monitor you can actually Win + arrow key to move the dialog over to the other display. We need to find a way to bring the file dialog window to the front, or maybe just swap to borderless and then back to fullscreen/borderless fullscreen after we load something

**Comment by Koofa** [comment]
I tried pressing win + tab to move to windows explorer, but the game stopped responding and was completely stuck in fullscreen. :(

**Comment by cricketboy01** [comment]
Followup question: How do you ACCESS the level editor? I can't find it

**Comment by dch-GH** [comment]
> I tried pressing win + tab to move to windows explorer, but the game stopped responding and was completely stuck in fullscreen. :(

Yeah, its not responding because the file dialog has "captured" control. If you have a second monitor you can see win + tab doing something. Luckily its not an actual crash or freeze but it still sucks.
