### ISSUE TITLE
No gore shaders

### ISSUE THREAD

**Issue by grandmafighterjet** [studio-minus/madness-interactive-reloaded#78]
**Describe the bug**
when i kill them it doesnt show gore/bullet holes

**Steps to reproduce**
1. go to either game modes (experiment mode etc)

**Expected behavior**
The gore just wont show up

**Screenshots or video**
![Screenshot 2024-09-07 084045](https://github.com/user-attachments/assets/29ec6e6f-b94a-49d5-aa4d-cb791a585f8b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 0.48.4

**Comment by grandmafighterjet** [comment]
if anybody knows how to get the shaders please let me know

**Comment by mestiez** [comment]
Duplicate of #54
