### ISSUE TITLE
Crash when returning to menu right after destroying `lvl_train_machinist` train engine

### ISSUE THREAD

**Issue by zayphi** [studio-minus/madness-interactive-reloaded#88]
**Steps to reproduce**
1. Enter `lvl_train_machinist`
2. Destroy the train engine
3. Return to menu BEFORE winning the level

**Expected behavior**
Game does not crash by trying to invoke `Win` in the menu, which is likely the cause of the issue.

**Screenshots or video**

Video reproducing the issue
https://github.com/user-attachments/assets/98e7b6b9-ecbe-43f4-9190-7b8c84d881fc

Crash log
![image](https://github.com/user-attachments/assets/cd315df5-89ca-449e-9219-a7645a3d00b2)

**Desktop**
 - OS: Windows 10
 - Version 0.48.4

**Additional context**
All character customisation is reset to default after the crash. The lag spike experienced when destroying the train engine did not happen prior to my first time crashing.

**Comment by dch-GH** [comment]
Should be fixed in the next version. Thanks for including the crash report and video.
