### ISSUE TITLE
The game won't open

### ISSUE THREAD

**Issue by AAphobos** [studio-minus/madness-interactive-reloaded#95]
i extracted the files and tried to open mir.exe and it doesn't start
it doesn't show anything i checked task manager and it was not open i tried to open it several times but it's always the same thing

Desktop:
OS: Windows 10
version: 0.48.4

**Comment by mestiez** [comment]
Unclear

**Comment by bloodysnowlol** [comment]
same problem

**Comment by Finkk1337** [comment]
> Unclear

There are problems with the game and you just close your eyes, bravo, I have exactly the same problem but for some reason I can’t find a solution, oh yeah, because you close them all
