### ISSUE TITLE
No background in roof and in boss fight

### ISSUE THREAD

**Issue by JustANormalGuyyy** [studio-minus/madness-interactive-reloaded#97]
When i reached in roof theres no background but i continued...
when i reached in boss when im die and try to restart the game just crash soo please repair it

thats all!!!11!1

**Comment by SoapFif** [comment]
how do they even forget abt this lmao

**Comment by grandmafighterjet** [comment]
idk

**Comment by mestiez** [comment]
Duplicate of #37
